import type { UserRole } from '../types';

export const PERMISSIONS: Record<UserRole, string[]> = {
  super_admin: ['*'],
  company_admin: ['*'],
  hr_manager: [
    'employee:create',
    'employee:read',
    'employee:update',
    'document:manage',
    'leave:approve',
    'leave:create:own',
    'leave:read:own',
    'audit:read',
    'notification:read:own',
    'attendance:clock:own',
    'attendance:read:own',
    'attendance:read:team',
    'attendance:manage',
    'timesheet:read:own',
    'timesheet:submit:own',
    'timesheet:approve',
    'expense:create:own',
    'expense:read:own',
    'expense:approve',
    'expense:export',
    'report:read',
    'location:read',
    'location:manage',
    'rota:read',
    'rota:manage',
    'rota:read:own',
    'rota:claim:own',
    'payroll:read',
    'payroll:generate',
    'payroll:export',
  ],
  manager: [
    'leave:approve:team',
    'leave:create:own',
    'leave:read:own',
    'employee:read:team',
    'notification:read:own',
    'attendance:clock:own',
    'attendance:read:own',
    'attendance:read:team',
    'timesheet:read:own',
    'timesheet:submit:own',
    'timesheet:approve:team',
    'expense:create:own',
    'expense:read:own',
    'expense:approve:team',
    'rota:read',
    'rota:manage',
    'rota:read:own',
    'rota:claim:own',
  ],
  employee: [
    'leave:create:own',
    'leave:read:own',
    'document:read:own',
    'profile:update:own',
    'notification:read:own',
    'attendance:clock:own',
    'attendance:read:own',
    'timesheet:read:own',
    'timesheet:submit:own',
    'expense:create:own',
    'expense:read:own',
    'rota:read:own',
    'rota:claim:own',
  ],
};

export const hasPermission = (role: UserRole, permission: string): boolean => {
  const rolePermissions = PERMISSIONS[role];
  if (rolePermissions.includes('*')) return true;
  return rolePermissions.includes(permission);
}
